set_property PACKAGE_PIN P20 [get_ports mic_sck]
set_property PACKAGE_PIN N20 [get_ports mic_ws]
set_property IOSTANDARD LVCMOS33 [get_ports mic_sck]
set_property IOSTANDARD LVCMOS33 [get_ports mic_ws]
set_property PACKAGE_PIN P18 [get_ports {mic_sd[3]}]
set_property PACKAGE_PIN N17 [get_ports {mic_sd[2]}]
set_property PACKAGE_PIN P19 [get_ports {mic_sd[1]}]
set_property PACKAGE_PIN N18 [get_ports {mic_sd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_sd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_sd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_sd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_sd[0]}]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

create_clock -period 20.000 -waveform {0.000 10.000} [get_ports clk]
